artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_url: https://drive.google.com/file/d/1gK9DTZ1ReF2a-LX1N0fEveYbQUTXDaHA/view?usp=sharing
    local_data_file: artifacts/data_ingestion/data.zip
    unzip_dir: artifacts/data_ingestion

prepare_base_model:
    root_dir: artifacts/prepare_base_model
    base_model_path: artifacts/prepare_base_model/model.keras
    updated_base_model_path: artifacts/prepare_base_model/model_updated.keras

model_training:
    root_dir: artifacts/model_training
    trained_model_path: artifacts/model_training/model.keras